AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless Image Uploader

  A serverless image upload and retrieval service built with AWS Lambda, S3, and DynamoDB using TypeScript.

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs24.x
    Handler: dist/handler.handler
    Architectures:
      - x86_64

Resources:
  ItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: Single handler for / routes (GET/POST/DELETE)
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts