AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless Image Uploader

  A serverless image upload and retrieval service built with AWS Lambda, S3, and DynamoDB using TypeScript.

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs24.x
    Handler: dist/handler.handler
    Architectures:
      - x86_64
    Environment:
      Variables:
        IMAGES_TABLE: !Ref ImagesTable
        BUCKET_NAME: !Sub "${ImageBucket}"

Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "serverless-images-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Suspended

  ImagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "ImagesTable-${AWS::AccountId}-${AWS::Region}"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: Single handler for / routes (GET/POST/DELETE)
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource: !Sub "arn:aws:s3:::${ImageBucket}/*"
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:DeleteItem
              Resource: !GetAtt ImagesTable.Arn
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
