AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless Image Uploader

  A serverless image upload and retrieval service built with AWS Lambda, S3, and DynamoDB using TypeScript.

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    Handler: dist/handler.handler
    Architectures:
      - x86_64
    Environment:
      Variables:
        TABLE_NAME: !Ref ImagesTable
        BUCKET_NAME: !Ref "${ImageBucket}"
  Api:
    BinaryMediaTypes:
      - 'multipart/form-data'

Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "serverless-images-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Suspended

  ImagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "ImagesTable-${AWS::AccountId}-${AWS::Region}"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: Single handler for / routes (GET/POST/DELETE)
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - GET
            - POST
            - DELETE
          AllowHeaders:
            - '*'
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource: !Sub "arn:aws:s3:::${ImageBucket}/*"
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:DeleteItem
              Resource: !GetAtt ImagesTable.Arn
      Events:
        UploadImage:
          Type: Api
          Properties:
            Path: /upload
            Method: POST
        GetImage:
          Type: Api
          Properties:
            Path: /image/{id}
            Method: GET
        DeleteImage:
          Type: Api
          Properties:
            Path: /{id}
            Method: DELETE

Outputs:
  ImageFunctionUrl:
    Description: "Lambda Function URL for the image handler"
    Value: !GetAtt ImageFunctionUrl.FunctionUrl
